
--CRIANDO DATABASE E UTILIZANDO
CREATE DATABASE inlock_games_tarde;
USE inlock_games_tarde;
GO

--CRIANDO TABELA ESTUDIOS
CREATE TABLE Estudios(
	idEstudio		INT PRIMARY KEY IDENTITY,
	nomeEstudio		VARCHAR(200) UNIQUE NOT NULL,
);
GO

--CRIANDO TABELA JOGOS
CREATE TABLE Jogos(
	idJogo			INT PRIMARY KEY IDENTITY,
	nomeJogo		VARCHAR(200) NOT NULL,
	descrição		VARCHAR(200) NOT NULL,
	dataLancamento	DATE NOT NULL,
	valor			VARCHAR	(200) NOT NULL,
	idEstudio		INT FOREIGN KEY REFERENCES Estudios(idEstudio)
);
GO

--CRIANDO TABELA TIPOS DE USUARIOS
CREATE TABLE TiposUsuarios(
	idTipoUsuario	INT PRIMARY KEY IDENTITY,
	titulo			VARCHAR(200) NOT NULL,
);
GO


--CRIANDO TABELA DOS USUARIOS
CREATE TABLE Usuarios(
	idUsuario		INT PRIMARY KEY IDENTITY,
	email			VARCHAR (200) NOT NULL,
	senha			VARCHAR(50)	NOT NULL,
	idTipoUsuario	INT FOREIGN KEY REFERENCES TiposUsuarios(idTipoUsuario)
);
GO



