CREATE DATABASE exercicio_locadora;
GO
USE exercicio_locadora;
GO

CREATE TABLE empresa(
	idEmpresa INT PRIMARY KEY IDENTITY,
	nomeEmpresa VARCHAR (200) NOT NULL
);
GO

CREATE TABLE Clientes(
	idCliente INT PRIMARY KEY IDENTITY,
	nomeCliente  VARCHAR (200) NOT NULL,
	CPF VARCHAR (11) NOT NULL,
);
GO

CREATE TABLE Marcas(
	idMarca INT PRIMARY KEY IDENTITY,
	Marca VARCHAR(200) NOT NULL
);
GO

CREATE TABLE Modelos(
	idModelo INT PRIMARY KEY IDENTITY,
	idMarca INT	FOREIGN KEY	REFERENCES Marcas(idMarca),
	descricao VARCHAR (200) NOT NULL
);
GO

CREATE TABLE Veiculos(
	idVeiculo INT PRIMARY KEY IDENTITY,
	idEmpresa INT FOREIGN KEY REFERENCES empresa(idEmpresa),
	idModelo INT FOREIGN KEY REFERENCES Modelos(idModelo),
	placa VARCHAR(20) NOT NULL
);
GO

CREATE TABLE Alugueis(
	idAluguel INT PRIMARY KEY IDENTITY,
	idVeiculo INT FOREIGN KEY REFERENCES Veiculos(idVeiculo),
	idCliente INT FOREIGN KEY REFERENCES Clientes(idCliente),
	DataInicio DATETIME NOT NULL,	
	DataFim  DATETIME NOT NULL

);
GO


